# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a698a51eb6fcbfa7836035bf1d34c577628ac4889d938e3a99a351e9ed558532bf242d648e68b544024e46e28663142020595dd151dc54263465afd2a7f5321c

test:
  secret_key_base: ccdf0539fe71258cc415184823f3b29ec7b305f4866dae469a6c1881fa8ae6506d1bdd10d78ab56cf616aab499a496aa8e14b6d9814c444e2df8b36364b15fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a698a51eb6fcbfa7836035bf1d34c577628ac4889d938e3a99a351e9ed558532bf242d648e68b544024e46e28663142020595dd151dc54263465afd2a7f5321c
  